schema {
  query: RootQuery
}

interface ContentNode {
  databaseId: Int!
}

type Page implements ContentNode {
  databaseId: Int!
}

type RootQuery {
  legacyProjects: [LegacyProject]
  siraBrand: SiraBrand!
  siraProjects(first: Int, after: String): SiraProjectConnection
}

type LegacyProject {
  id: ID!
}

type SiraBrand {
  key: String!
  legacyLogoText: String
}

type SiraProjectConnection {
  nodes: [SiraProject!]!
}

type SiraProject {
  id: ID!
  title: String
  projectDetails: ProjectDetails
}

type ProjectDetails {
  status: String
  statistics: [ProjectDetailsStatistics]
}

type ProjectDetailsStatistics {
  label: String
  value: String
}
