fragment EditorialSingleMedia on MediaItem {
  databaseId
  sourceUrl
  altText
  isRestricted
  mediaDetails {
    width
    height
  }
}

fragment EditorialSingleFeaturedImage on NodeWithFeaturedImageToMediaItemConnectionEdge {
  node {
    ...EditorialSingleMedia
  }
}

query SiraEditorialSingle($uri: String!) {
  nodeByUri(uri: $uri) {
    __typename
    ... on ContentNode {
      databaseId
      contentTypeName
      uri
      date
      modified
      isRestricted
    }
    ... on SiraNewsItem {
      title
      excerpt
      content(format: RENDERED)
      featuredImage {
        ...EditorialSingleFeaturedImage
      }
    }
    ... on SiraInsight {
      title
      excerpt
      content(format: RENDERED)
      featuredImage {
        ...EditorialSingleFeaturedImage
      }
    }
    ... on SiraArticle {
      title
      excerpt
      content(format: RENDERED)
      featuredImage {
        ...EditorialSingleFeaturedImage
      }
    }
    ... on SiraPressRelease {
      title
      excerpt
      content(format: RENDERED)
      featuredImage {
        ...EditorialSingleFeaturedImage
      }
    }
  }
}
