query SiraNavigation(
  $primary: MenuLocationEnum = PRIMARY
  $footer: MenuLocationEnum = FOOTER
  $legal: MenuLocationEnum = LEGAL
) {
  primary: menus(first: 2, where: { location: $primary }) {
    ...SiraNavigationMenuCollection
  }
  footer: menus(first: 2, where: { location: $footer }) {
    ...SiraNavigationMenuCollection
  }
  legal: menus(first: 2, where: { location: $legal }) {
    ...SiraNavigationMenuCollection
  }
}

fragment SiraNavigationMenuCollection on RootQueryToMenuConnection {
  pageInfo {
    hasNextPage
  }
  nodes {
    databaseId
    isRestricted
    locations
    menuItems(first: 200) {
      pageInfo {
        hasNextPage
      }
      nodes {
        databaseId
        isRestricted
        label
        order
        parentDatabaseId
        path
        target
        url
      }
    }
  }
}
