query SiraProjects($first: Int!, $after: String) {
  siraProjects(first: $first, after: $after) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      databaseId
      title
      uri
      excerpt
      date
      isRestricted
      siraLocale {
        code
      }
      businessUnit: siraBusinessUnits(first: 1) {
        nodes {
          ... on SiraBusinessUnit {
            slug
            name
          }
        }
      }
      featuredImage {
        node {
          databaseId
          sourceUrl
          altText
          mediaDetails {
            width
            height
          }
        }
      }
      projectDetails {
        subtitle
        location
        status
        relatedCompany(first: 1) {
          nodes {
            ... on SiraCompany {
              title
              businessUnit: siraBusinessUnits(first: 1) {
                nodes {
                  ... on SiraBusinessUnit {
                    slug
                    name
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
