query SiraProjects($first: Int!, $after: String) {
  siraProjects(first: $first, after: $after) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      databaseId
      title
      uri
      excerpt
      isRestricted
      featuredImage {
        node {
          databaseId
          sourceUrl
          altText
          mediaDetails {
            width
            height
          }
        }
      }
      projectDetails {
        subtitle
        location
        status
      }
    }
  }
}
