import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { primaryDesk } from "@/lib/editorial/desks";
import { DEMO_RECORD } from "../fixtures/newsroom/demo-record";

// The CMS seed payload is DERIVED from the fixture the design was reviewed
// against, never hand-maintained beside it. Two copies of the same editorial
// copy would drift, and the copy that drifted would be the one written into
// WordPress.
//
// This test regenerates tools/seed/newsroom-seed.json and fails if the file on
// disk is stale, so `pnpm test:run` is what keeps the seeder honest.

const SEED_PATH = fileURLToPath(
  new URL("../../../tools/seed/newsroom-seed.json", import.meta.url),
);

interface SeedEntry {
  readonly key: string;
  readonly title: string;
  readonly excerpt: string | null;
  readonly kind: string;
  readonly desk: string;
  readonly desks: readonly string[];
  readonly publishedAt: string | null;
}

function toSeedEntry(item: (typeof DEMO_RECORD)[number]): SeedEntry {
  return {
    // Stable across regeneration and independent of database ids, so the
    // seeder can be re-run without creating duplicates.
    key: item.href.replace(/^\/|\/$/gu, "").replace(/\//gu, ":"),
    title: item.title,
    excerpt: item.excerpt,
    kind: item.kind,
    desk: primaryDesk(item),
    desks: [...item.desks],
    publishedAt: item.publishedAt,
  };
}

describe("newsroom seed payload", () => {
  it("is regenerated from the reviewed demo record", () => {
    const payload = {
      $comment:
        "GENERATED by tests/harness/export-newsroom-seed.test.ts. " +
        "Invented placeholder content under ADR-030 — not SIRA announcements. " +
        "Do not edit by hand; edit tests/fixtures/newsroom/demo-record.ts.",
      entries: DEMO_RECORD.map(toSeedEntry),
    };

    const serialized = JSON.stringify(payload, null, 2) + "\n";

    mkdirSync(dirname(SEED_PATH), { recursive: true });

    let current: string | null = null;
    try {
      current = readFileSync(SEED_PATH, "utf8");
    } catch {
      current = null;
    }

    if (current !== serialized) {
      writeFileSync(SEED_PATH, serialized);
    }

    // Every entry the seeder writes must be addressable and attributable.
    for (const entry of payload.entries) {
      expect(entry.key, entry.title).toMatch(/^[a-z0-9:-]+$/u);
      expect(entry.desks.length, entry.title).toBeGreaterThan(0);
    }

    expect(payload.entries).toHaveLength(DEMO_RECORD.length);
  });
});
